/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusRepoIdRouteImport } from './routes/status.$repo.$id'
import { Route as SearchRepoIdRouteImport } from './routes/search.$repo.$id'
import { Route as ModlistRepoIdRouteImport } from './routes/modlist.$repo.$id'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRepoIdRoute = StatusRepoIdRouteImport.update({
  id: '/$repo/$id',
  path: '/$repo/$id',
  getParentRoute: () => StatusRoute,
} as any)
const SearchRepoIdRoute = SearchRepoIdRouteImport.update({
  id: '/search/$repo/$id',
  path: '/search/$repo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ModlistRepoIdRoute = ModlistRepoIdRouteImport.update({
  id: '/modlist/$repo/$id',
  path: '/modlist/$repo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discord': typeof DiscordRoute
  '/gallery': typeof GalleryRoute
  '/status': typeof StatusRouteWithChildren
  '/modlist/$repo/$id': typeof ModlistRepoIdRoute
  '/search/$repo/$id': typeof SearchRepoIdRoute
  '/status/$repo/$id': typeof StatusRepoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discord': typeof DiscordRoute
  '/gallery': typeof GalleryRoute
  '/status': typeof StatusRouteWithChildren
  '/modlist/$repo/$id': typeof ModlistRepoIdRoute
  '/search/$repo/$id': typeof SearchRepoIdRoute
  '/status/$repo/$id': typeof StatusRepoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discord': typeof DiscordRoute
  '/gallery': typeof GalleryRoute
  '/status': typeof StatusRouteWithChildren
  '/modlist/$repo/$id': typeof ModlistRepoIdRoute
  '/search/$repo/$id': typeof SearchRepoIdRoute
  '/status/$repo/$id': typeof StatusRepoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discord'
    | '/gallery'
    | '/status'
    | '/modlist/$repo/$id'
    | '/search/$repo/$id'
    | '/status/$repo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discord'
    | '/gallery'
    | '/status'
    | '/modlist/$repo/$id'
    | '/search/$repo/$id'
    | '/status/$repo/$id'
  id:
    | '__root__'
    | '/'
    | '/discord'
    | '/gallery'
    | '/status'
    | '/modlist/$repo/$id'
    | '/search/$repo/$id'
    | '/status/$repo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscordRoute: typeof DiscordRoute
  GalleryRoute: typeof GalleryRoute
  StatusRoute: typeof StatusRouteWithChildren
  ModlistRepoIdRoute: typeof ModlistRepoIdRoute
  SearchRepoIdRoute: typeof SearchRepoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$repo/$id': {
      id: '/status/$repo/$id'
      path: '/$repo/$id'
      fullPath: '/status/$repo/$id'
      preLoaderRoute: typeof StatusRepoIdRouteImport
      parentRoute: typeof StatusRoute
    }
    '/search/$repo/$id': {
      id: '/search/$repo/$id'
      path: '/search/$repo/$id'
      fullPath: '/search/$repo/$id'
      preLoaderRoute: typeof SearchRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modlist/$repo/$id': {
      id: '/modlist/$repo/$id'
      path: '/modlist/$repo/$id'
      fullPath: '/modlist/$repo/$id'
      preLoaderRoute: typeof ModlistRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StatusRouteChildren {
  StatusRepoIdRoute: typeof StatusRepoIdRoute
}

const StatusRouteChildren: StatusRouteChildren = {
  StatusRepoIdRoute: StatusRepoIdRoute,
}

const StatusRouteWithChildren =
  StatusRoute._addFileChildren(StatusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscordRoute: DiscordRoute,
  GalleryRoute: GalleryRoute,
  StatusRoute: StatusRouteWithChildren,
  ModlistRepoIdRoute: ModlistRepoIdRoute,
  SearchRepoIdRoute: SearchRepoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
